name: buf-pull-request
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-lint-action@v1
      - uses: bufbuild/buf-breaking-action@v1
        with:
          input: protos
          against: 'https://github.com/${GITHUB_REPOSITORY}.git#branch=master,ref=HEAD~1,subdir=protos'
