name: buf-push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-lint-action@v1
      - uses: bufbuild/buf-breaking-action@v1
        with:
          input: proto
          against: 'https://github.com/${GITHUB_REPOSITORY}.git#branch=master,ref=HEAD~1,subdir=proto'
      - uses: bufbuild/buf-breaking-action@v1
        with:
          input: extensions
          against: 'https://github.com/${GITHUB_REPOSITORY}.git#branch=master,ref=HEAD~1,subdir=extensions'
      - uses: bufbuild/buf-push-action@v1
        with:
          input: extensions
          buf_token: ${{ secrets.BUF_TOKEN }}
      - uses: bufbuild/buf-push-action@v1
        with:
          input: proto
          buf_token: ${{ secrets.BUF_TOKEN }}
